/**
 * Looks up the correct YouTube channel ID for each artist by name-searching
 * the YouTube Data API, then prints a SQL migration to update them.
 * 
 * Run with:
 *   cd backend
 *   npx ts-node --esm scripts/fix-channel-ids.ts
 */

import * as dotenv from 'dotenv'
import * as path from 'path'
import * as fs from 'fs'

dotenv.config({ path: path.resolve(__dirname, '../../.env') })

const YOUTUBE_API_KEY = process.env.YOUTUBE_API_KEY!
const YOUTUBE_BASE    = 'https://www.googleapis.com/youtube/v3'

const ARTISTS = [
  'Sanjay Subrahmanyan',
  'T.M. Krishna',
  'Aruna Sairam',
  'Sudha Raghunathan',
  'Bombay Jayashri',
  'Nithyashree Mahadevan',
  'O.S. Arun',
  'Unnikrishnan',
  'Sowmya',
  'Ranjani & Gayatri',
  'Vijay Siva',
  'K.J. Yesudas',
  'Abhishek Raghuram',
  'Kadri Gopalnath',
  'Chitravina N. Ravikiran',
  'Ambi Subramaniam',
  'Ganesh & Kumaresh',
  'Mysore Manjunath',
  'Music Academy Chennai',
  'Brahma Gana Sabha',
  'Narada Gana Sabha',
  'Kartik Fine Arts',
  'Carnatica',
  'Sangeet Mahotsav',
  'Classical Music India',
  'M.S. Subbulakshmi',
  'L. Subramaniam',
  // Additional artists from 003 migration without channel IDs
  'Balamurali Krishna',
  'Lalgudi Jayaraman',
  'N. Ramani',
  'Mandolin U. Srinivas',
  'Vikku Vinayakram',
  'T.V. Sankaranarayanan',
  'Maharajapuram Santhanam',
  'K.V. Narayanaswamy',
  'M. Balamurali Krishna',
  'Trichy Sankaran',
  'Yesudas',
  'Voleti Venkateswarulu',
]

async function findChannel(artistName: string): Promise<{ id: string; title: string } | null> {
  const params = new URLSearchParams({
    part:       'snippet',
    type:       'channel',
    q:          `${artistName} carnatic music`,
    maxResults: '3',
    key:        YOUTUBE_API_KEY,
  })

  const res  = await fetch(`${YOUTUBE_BASE}/search?${params}`)
  const data = await res.json()

  if (!res.ok) {
    console.error(`API error for ${artistName}:`, data.error?.message)
    return null
  }

  if (!data.items?.length) {
    console.log(`  ✗ No channel found for: ${artistName}`)
    return null
  }

  // Pick best match: prefer channel whose title contains the artist name
  const items = data.items as Array<{
    id: { channelId: string }
    snippet: { channelTitle: string }
  }>

  const best =
    items.find(i => i.snippet.channelTitle.toLowerCase().includes(artistName.split(' ')[1]?.toLowerCase() || '')) ||
    items[0]

  return { id: best.id.channelId, title: best.snippet.channelTitle }
}

async function main() {
  console.log('Looking up channel IDs for all artists...\n')

  const updates: { name: string; channelId: string; channelTitle: string }[] = []
  const notFound: string[] = []

  for (const artist of ARTISTS) {
    process.stdout.write(`  ${artist}... `)
    const result = await findChannel(artist)
    if (result) {
      console.log(`✓ ${result.id} (${result.title})`)
      updates.push({ name: artist, channelId: result.id, channelTitle: result.title })
    } else {
      notFound.push(artist)
    }
    // Rate limit: 1 search = 100 units, sleep 200ms between calls
    await new Promise(r => setTimeout(r, 200))
  }

  // Generate SQL migration
  const sql = [
    '-- Migration: Update artists with correct YouTube channel IDs',
    '-- Auto-generated by fix-channel-ids.ts',
    '',
    ...updates.map(u =>
      `UPDATE artists SET youtube_channel_id = '${u.channelId}' WHERE name ILIKE '%${u.name.replace(/'/g, "''")}%';`
    ),
    '',
    '-- Not found:',
    ...notFound.map(n => `-- ${n}`),
  ].join('\n')

  const outPath = path.resolve(__dirname, '../supabase/migrations/004_fix_channel_ids.sql')
  fs.writeFileSync(outPath, sql)

  console.log('\n✅ SQL migration written to:', outPath)
  console.log(`   ${updates.length} channel IDs found, ${notFound.length} not found`)
  console.log(`   Approx quota used: ${ARTISTS.length * 100} units`)
}

main().catch(console.error)
