-- Migration: Update artists with correct YouTube channel IDs
-- Auto-generated by fix-channel-ids.ts

UPDATE artists SET youtube_channel_id = 'UCOwMXGjxYotFyVdby5i4m1g' WHERE name ILIKE '%Sanjay Subrahmanyan%';
UPDATE artists SET youtube_channel_id = 'UCIFdoNjZ2DlJVBmIWQPbR3w' WHERE name ILIKE '%T.M. Krishna%';
UPDATE artists SET youtube_channel_id = 'UCXPApknTM88FqgG0zjtItfg' WHERE name ILIKE '%Aruna Sairam%';
UPDATE artists SET youtube_channel_id = 'UC1rP5IjJ_8iffOYC8ZFVARg' WHERE name ILIKE '%Sudha Raghunathan%';
UPDATE artists SET youtube_channel_id = 'UCg1vz4A18N6KWzfuh7fNxgQ' WHERE name ILIKE '%Bombay Jayashri%';
UPDATE artists SET youtube_channel_id = 'UChcOQTBdeLA4LCiX9YJNeTQ' WHERE name ILIKE '%Nithyashree Mahadevan%';
UPDATE artists SET youtube_channel_id = 'UCuvtiMrIc5RxtPp0HO_0N_A' WHERE name ILIKE '%O.S. Arun%';
UPDATE artists SET youtube_channel_id = 'UCuL0StnzfmsjkdMi-pcsphg' WHERE name ILIKE '%Unnikrishnan%';
UPDATE artists SET youtube_channel_id = 'UCgekUzctlt0TTe2f2qwxlBg' WHERE name ILIKE '%Sowmya%';
UPDATE artists SET youtube_channel_id = 'UCcHlfUF_W1ImPmNEVhIsO2Q' WHERE name ILIKE '%Ranjani & Gayatri%';
UPDATE artists SET youtube_channel_id = 'UCpacO0JRAF2UEC1FPyhjdMw' WHERE name ILIKE '%Vijay Siva%';
UPDATE artists SET youtube_channel_id = 'UCWUjYIas3aSW65lQOpGiRrg' WHERE name ILIKE '%K.J. Yesudas%';
UPDATE artists SET youtube_channel_id = 'UCPDbU-Q9EIDoc0sbrks7-Lg' WHERE name ILIKE '%Abhishek Raghuram%';
UPDATE artists SET youtube_channel_id = 'UCXTHrFXtxkxuCUAchpx28pA' WHERE name ILIKE '%Kadri Gopalnath%';
UPDATE artists SET youtube_channel_id = 'UClaSm2rq1_6G4ILHK5B9Qxw' WHERE name ILIKE '%Chitravina N. Ravikiran%';
UPDATE artists SET youtube_channel_id = 'UClHR6H852znWED_LNu0o0BA' WHERE name ILIKE '%Ambi Subramaniam%';
UPDATE artists SET youtube_channel_id = 'UCIeJ6bUAY1AdhbhTFgr7Qfw' WHERE name ILIKE '%Ganesh & Kumaresh%';
UPDATE artists SET youtube_channel_id = 'UCZaGID8moGTBGxfN8WeWBsA' WHERE name ILIKE '%Mysore Manjunath%';
UPDATE artists SET youtube_channel_id = 'UCKmE9i2iW0KaqgSxVFYmZUw' WHERE name ILIKE '%Music Academy Chennai%';
UPDATE artists SET youtube_channel_id = 'UCfDNeYjoqsfOhU-nX_g8GoA' WHERE name ILIKE '%Brahma Gana Sabha%';
UPDATE artists SET youtube_channel_id = 'UCE5dTxYYk-zRi7i8q7F9OZg' WHERE name ILIKE '%Narada Gana Sabha%';
UPDATE artists SET youtube_channel_id = 'UCLEaUPYUV3qZlHhOM-44R1Q' WHERE name ILIKE '%Kartik Fine Arts%';
UPDATE artists SET youtube_channel_id = 'UCmZlcYYHVjF-0EZ0fj_-B6g' WHERE name ILIKE '%Carnatica%';
UPDATE artists SET youtube_channel_id = 'UCMPrP1A_YqqmEKU4x4hMWbA' WHERE name ILIKE '%Sangeet Mahotsav%';
UPDATE artists SET youtube_channel_id = 'UCdWghuUa0qb1bgt0fdX6i0w' WHERE name ILIKE '%Classical Music India%';
UPDATE artists SET youtube_channel_id = 'UCPUPn_F9y9VexJkTAW2lq_g' WHERE name ILIKE '%M.S. Subbulakshmi%';
UPDATE artists SET youtube_channel_id = 'UCdYNQApXy7MN4ynEzWf1HlQ' WHERE name ILIKE '%L. Subramaniam%';
UPDATE artists SET youtube_channel_id = 'UC1C05NyYICFB2mVGn9_ttEw' WHERE name ILIKE '%Balamurali Krishna%';
UPDATE artists SET youtube_channel_id = 'UC8WS_h89dHSBZkmeA2UJXmw' WHERE name ILIKE '%Lalgudi Jayaraman%';
UPDATE artists SET youtube_channel_id = 'UCuPTax38Zve2zo35C-wsT9Q' WHERE name ILIKE '%N. Ramani%';
UPDATE artists SET youtube_channel_id = 'UCSl-h6hw77t_dOlIhLXmmIQ' WHERE name ILIKE '%Mandolin U. Srinivas%';
UPDATE artists SET youtube_channel_id = 'UCDfbKf05_FsFHTzqqNtGCLg' WHERE name ILIKE '%Vikku Vinayakram%';
UPDATE artists SET youtube_channel_id = 'UCW6naWCHaFV2CTG1t4EO1wg' WHERE name ILIKE '%T.V. Sankaranarayanan%';
UPDATE artists SET youtube_channel_id = 'UC-mcBpvobzjRdJBmCaLY3qQ' WHERE name ILIKE '%Maharajapuram Santhanam%';
UPDATE artists SET youtube_channel_id = 'UCNL3GG1YFOvyQZQ_cwEG1lA' WHERE name ILIKE '%K.V. Narayanaswamy%';
UPDATE artists SET youtube_channel_id = 'UC1C05NyYICFB2mVGn9_ttEw' WHERE name ILIKE '%M. Balamurali Krishna%';
UPDATE artists SET youtube_channel_id = 'UCbOJ_8uRclrqOkwR-qub4Sg' WHERE name ILIKE '%Trichy Sankaran%';
UPDATE artists SET youtube_channel_id = 'UCWUjYIas3aSW65lQOpGiRrg' WHERE name ILIKE '%Yesudas%';
UPDATE artists SET youtube_channel_id = 'UCR-M58NtfhVyFgxeWETqxGA' WHERE name ILIKE '%Voleti Venkateswarulu%';

-- Not found: